name: Release Excel Data View Plugin

on:
  push:
    tags:
      - 'v*' # 匹配版本标签，如 v1.0.0, v1.0.1, etc.
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Extract version from tag
      id: version
      run: |
        # 从标签中提取版本号 (如 v1.0.0 -> 1.0.0)
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
        
    - name: Update pom.xml version
      run: |
        # 更新pom.xml中的版本号
        mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }}
        mvn versions:commit
        
    - name: Build with Maven
      run: |
        mvn clean package -DskipTests
        
    - name: Check build artifacts
      run: |
        echo "检查构建产物..."
        ls -la target/
        if [ ! -f "target/excelDataView-${{ env.RELEASE_VERSION }}.jar" ]; then
          echo "❌ 基础JAR文件不存在"
          exit 1
        fi
        if [ ! -f "target/excelDataView-${{ env.RELEASE_VERSION }}-jar-with-dependencies.jar" ]; then
          echo "❌ 包含依赖的JAR文件不存在"
          exit 1
        fi
        echo "✅ 构建产物检查通过"
        
    - name: Create Release Notes
      id: release-notes
      run: |
        # 创建发布说明
        cat > RELEASE_NOTES.md << EOF
        ## Excel Data View Plugin v${{ env.RELEASE_VERSION }}
        
        ### 功能特性
        - 在Burp Suite中显示Excel响应数据的自定义标签页
        - 支持XLS和XLSX格式的Excel文件
        - 支持多工作表显示
        - 自动检测HTTP响应中的Excel数据
        - 修复中文编码问题
        - 使用Burp Suite日志系统进行调试
        
        ### 安装方法
        1. 下载 \`excelDataView-${{ env.RELEASE_VERSION }}-jar-with-dependencies.jar\`
        2. 在Burp Suite中导入该JAR文件
        3. 插件会自动注册并在Excel响应中显示"Excel数据"标签页
        
        ### 使用说明
        - 当HTTP响应包含Excel格式数据时，会自动显示"Excel数据"标签页
        - 支持查看多个工作表
        - 自动处理中文编码问题
        
        ### 更新日志
        - 改进了HTTP响应数据提取
        - 使用Burp Suite统一的日志系统
        - 增强了错误处理和调试信息
        - 支持模块化设计
        - 添加完整的项目文档和开源协议
        
        ### 技术架构
        - Java 17 + Maven
        - Apache POI for Excel处理
        - Burp Suite Extender API
        - Swing UI组件
        
        ---
        
        *此版本由GitHub Actions自动构建发布*
        EOF
        
    - name: Debug GitHub Token
      run: |
        echo "GitHub Token 权限检查..."
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "Ref Name: ${{ github.ref_name }}"
        echo "Actor: ${{ github.actor }}"
        
    - name: Create Release
      id: create-release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Excel Data View Plugin v${{ env.RELEASE_VERSION }}
        body_path: RELEASE_NOTES.md
        files: |
          target/excelDataView-${{ env.RELEASE_VERSION }}.jar
          target/excelDataView-${{ env.RELEASE_VERSION }}-jar-with-dependencies.jar
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Release Status
      if: always()
      run: |
        if [ "${{ steps.create-release.outcome }}" = "success" ]; then
          echo "✅ Release 创建成功"
          echo "Release URL: ${{ steps.create-release.outputs.url }}"
        else
          echo "❌ Release 创建失败"
          echo "请检查权限配置和网络连接"
        fi
        
    - name: Commit version changes
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pom.xml
        git commit -m "Release version ${{ env.RELEASE_VERSION }}" || echo "No changes to commit"
        git push || echo "Failed to push version changes"
        
    - name: Build Summary
      run: |
        echo "## 构建完成 ✅" >> $GITHUB_STEP_SUMMARY
        echo "- **版本**: ${{ env.RELEASE_VERSION }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Release**: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **JAR文件**: excelDataView-${{ env.RELEASE_VERSION }}-jar-with-dependencies.jar" >> $GITHUB_STEP_SUMMARY